name: Simple MLOps Workflow

on:
  push:  
    branches:
      - main  

jobs:
  execute-notebooks:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.14'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r kaggle_requirements.txt

    # Step 4: Execute notebooks
    - name: Run Jupyter Notebook
      env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
      run: |
        pip install nbconvert
        jupyter nbconvert --execute --to notebook --inplace notebooks/trash-image-classification.ipynb
